<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="ISW-250217-OEDF" failures="2" tests="2" name="Test Execution" time="0.068" errors="0" timestamp="2025-03-17T17:17:26 WAT">
  <testcase classname="testCases.TC001_User_Registration" name="successful_user_registration" time="0.013">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.apache.logging.log4j.Logger.info(String)&amp;quot; because &amp;quot;this.logger&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.logging.log4j.Logger.info(String)" because "this.logger" is null
at testCases.TC001_User_Registration.successful_user_registration(TC001_User_Registration.java:18)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- successful_user_registration -->
  <testcase classname="testCases.TC002_User_Authentication" name="successful_login" time="0.012">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.apache.logging.log4j.Logger.info(String)&amp;quot; because &amp;quot;this.logger&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.logging.log4j.Logger.info(String)" because "this.logger" is null
at testCases.TC002_User_Authentication.successful_login(TC002_User_Authentication.java:16)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- successful_login -->
  <testcase classname="testCases.TC003_User_AuthenticationDDT" name="successful_login_DDT" time="0.0">
    <ignored/>
  </testcase> <!-- successful_login_DDT -->
</testsuite> <!-- Test Execution -->
