<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="ISW-250217-OEDF" failures="1" tests="2" name="Test" time="45.034" errors="0" timestamp="2025-03-18T12:58:27 WAT">
  <testcase classname="testCases.TC001_User_Registration" name="successful_user_registration" time="8.57"/>
  <testcase classname="testCases.TC002_User_Authentication" name="successful_login" time="12.664">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC002_User_Authentication.successful_login(TC002_User_Authentication.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- successful_login -->
  <testcase classname="testCases.TC003_User_AuthenticationDDT" name="successful_login_DDT" time="0.0">
    <ignored/>
  </testcase> <!-- successful_login_DDT -->
</testsuite> <!-- Test -->
